<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Description>Core classes and utilities for BepInEx Preloader</Description>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\BepInEx.Core\BepInEx.Core.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="HarmonyX" Version="2.16.1" />
        <PackageReference Include="MonoMod.Utils" Version="25.0.12"/>
    </ItemGroup>
</Project>
